version: '3.8'

services:
  # Serviço da Aplicação (PHP 8.4 + Composer)
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - ./src:/var/www/html:cached
    networks:
      - laravel_network

  # Serviço do Nginx (Servidor Web)
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  # Serviço de Banco de Dados PostgreSQL
# Serviço de Banco de Dados PostgreSQL (MUDADO PARA pgsql)
  pgsql:
    image: postgres:16-alpine
    container_name: laravel_pgsql # Nome do container mudado
    restart: always
    environment:
      # Credenciais mudadas para corresponder ao seu .env padrão do Sail
      POSTGRES_DB: laravel
      POSTGRES_USER: sail
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - laravel_network

# Serviço Node.js/NPM (para Frontend/Vite)
  node:
    image: node:20-alpine # Imagem oficial Node.js LTS (recomendado para Laravel 12)
    container_name: laravel_node
    tty: true
    restart: always
    ports: # 👈 ADICIONE ESTE BLOCO
      - "5173:5173" # Mapeia a porta do Vite para o Host
    volumes:
      - ./src:/var/www/html:cached # Mapeia a pasta do seu projeto
    working_dir: /var/www/html # Onde os comandos 'npm' serão executados
    networks:
      - laravel_network
volumes:
  postgres_data:
    driver: local

networks:
  laravel_network:
    driver: bridge

